// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-dCHyEh58YRsjN879d1v9C8aAvtNTWW4',
    appId: '1:687295194504:web:cc944f62ced9bcf0ddc63d',
    messagingSenderId: '687295194504',
    projectId: 'news-assistant-8aea9',
    authDomain: 'news-assistant-8aea9.firebaseapp.com',
    storageBucket: 'news-assistant-8aea9.firebasestorage.app',
    measurementId: 'G-PL79J9EP92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYzChlBmJIqTImcvlNOFz4WiePjAnfJss',
    appId: '1:687295194504:android:9cb8ef2456b464f2ddc63d',
    messagingSenderId: '687295194504',
    projectId: 'news-assistant-8aea9',
    storageBucket: 'news-assistant-8aea9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5GFvefWBRx6TpqaNPlWCmzX4XQlkpXc8',
    appId: '1:687295194504:ios:014a63cebb7ae185ddc63d',
    messagingSenderId: '687295194504',
    projectId: 'news-assistant-8aea9',
    storageBucket: 'news-assistant-8aea9.firebasestorage.app',
    iosClientId: '687295194504-rp6ohi49o53smadblqkculvackv88tfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsAssistant',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5GFvefWBRx6TpqaNPlWCmzX4XQlkpXc8',
    appId: '1:687295194504:ios:014a63cebb7ae185ddc63d',
    messagingSenderId: '687295194504',
    projectId: 'news-assistant-8aea9',
    storageBucket: 'news-assistant-8aea9.firebasestorage.app',
    iosClientId: '687295194504-rp6ohi49o53smadblqkculvackv88tfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-dCHyEh58YRsjN879d1v9C8aAvtNTWW4',
    appId: '1:687295194504:web:e2cf60b018dab384ddc63d',
    messagingSenderId: '687295194504',
    projectId: 'news-assistant-8aea9',
    authDomain: 'news-assistant-8aea9.firebaseapp.com',
    storageBucket: 'news-assistant-8aea9.firebasestorage.app',
    measurementId: 'G-STQZ6QQ2DT',
  );
}
